
package com.analytics.scatterfit.config.constants;

public interface ErrorCodes {

	String GENERIC_EXCEPTION = "GENERIC_EXCEPTION";
	String EXISTING_USER_EXCEPTION = "EXISTING_USER_EXCEPTION";
	String AUTHENTICATION_FAILED_EXCEPTION = "AUTHENTICATION_FAILED_EXCEPTION";
	String EMAIL_NOT_SENT_EXCEPTION = "EMAIL_NOT_SENT_EXCEPTION";
	String USER_NOT_FOUND_EXCEPTION = "USER_NOT_FOUND_EXCEPTION";
	String INPUT_VALIDATION_EXCEPTION = "INPUT_VALIDATION_EXCEPTION";
	String LOGIN_FAILED_EXCEPTION = "LOGIN_FAILED_EXCEPTION";
	String REGISTRATION_FAILED_EXCEPTION = "REGISTRATION_FAILED_EXCEPTION";
}
